#!/bin/zsh

for i in */0/; do
	name=$(echo $i | sed 's#/0/##')
	awk '/\|e\|/'  ${i}raw.txt | tail -n 1 | cut -d '|' -f 3 | ths "let {f i [] = []; f i a = take i a:f i (drop i a); d ['\n'] = []; d (a:as) = a:d as}; getContents >>= putStr . unlines . map unwords . f 100 . words" > mat_e_${name}
	awk '/\|ux\|/' ${i}raw.txt | tail -n 1 | cut -d '|' -f 3 | tr ' ' '\n' > ux
	awk '/\|uy\|/' ${i}raw.txt | tail -n 1 | cut -d '|' -f 3 | tr ' ' '\n' > uy
	awk '/\|ut\|/' ${i}raw.txt | tail -n 1 | cut -d '|' -f 3 | tr ' ' '\n' > ut
	paste ux uy ut | awk '{print sqrt($1*$1+$2*$2)/$3}' > v
	cat v | ths "let {f i [] = []; f i a = take i a:f i (drop i a); d ['\n'] = []; d (a:as) = a:d as}; getContents >>= putStr . unlines . map unwords . f 100 . lines" > mat_v_${name}
    t=$(awk '/\|e\|/' ${i}raw.txt | tail -n 1 | cut -d '|' -f 1 | xargs printf "%.3f")
    awk '/\|T11-T22\|/' ${i}anisotropy.txt | cut -d '|' -f 1,3 | tr '|' ' ' > anisotropy_${name}
	cat anisotropy_${name}
	gnuplot -p -e 'set term png size 800,800 font "Arial,21"; set output "e.png"; set title "Energy density at t='$t' (fm/c)\ntrento Pb Pb default event"; set xlabel "x (fm)"; set ylabel "y (fm)"; set size ratio 1; set autoscale fix; plot "mat_e_'$name'" matrix with image noti'
	gnuplot -p -e 'set term png size 800,800 font "Arial,21"; set output "v.png"; set title "Velocity at t='$t' (fm/c)\ntrento Pb Pb default event"; set xlabel "x (fm)"; set ylabel "y (fm)"; set size ratio 1; set autoscale fix; plot "mat_v_'$name'" matrix with image noti'
	gnuplot -p -e 'set term png size 800,800 font "Arial,21"; set output "anisotropy.png"; set title "Momentum anisotropy as function of time\ntrento Pb Pb default event"; set xlabel "t (fm)"; set ylabel "<T11-T22>/<T11+T22>"; plot "anisotropy_'$name'" u 1:2 noti'
done
