actions:
  - [{Moments: [u]}, {TotalInterval: {from: 0, to: 10, total: 20}}]
  - [{Window: [[u],[0,0.3,0.63,0.8,0.9,1]]}, {TotalInterval: {from: 0, to: 10, total: 20}}]
  - [{StaticStructureFactor: [u]}, {TotalInterval: {from: 0, to: 10, total: 20}}]
  - [{DynamicStructureFactor: [u]}, {TotalInterval: {from: 0, to: 10, total: 20}}]
  - [{Correlation: [u]}, {TotalInterval: {from: 0, to: 10, total: 20}}]
config:
  t_max: 10
  dim: {D3: [[4,10],[4,10],[4,10]]}
  dirs: [X,Y,Z]
noises:
  - Normal:
      name: xi
symbols: |
  D := 1
  b(_x,_y,_z,*u) := u[x%x_size+x_size*(y%y_size+y_size*(z%z_size))]
  u' := D*(-6*b(x,y,z,u)+b(x+1,y,z,u)+b(x+x_size-1,y,z,u)+b(x,y+1,z,u)+b(x,y+y_size-1,z,u)+b(x,y,z+1,u)+b(x,y,z+z_size-1,u))*ivdx*ivdx + sqrt(2*D*ivdx*ivdt)*(b(x+1,y,z,xi)-b(x,y,z,xi))*ivdx
integrator:
  Euler:
    dt: 0.001
