data_files: [m2.txt]
actions:
  - [Moments, {Every: 30}]
    #  - [Correlation, {Every: 3}]
    #  - [StaticStructureFactor, {Interval: {from: 1, to: 4, every: 0.3}}]
    #  - [DynamicStructureFactor, {TotalInterval: {from: 1, to: 4, total: 0.7}}]
config:
  t_max: 100
  dim: {D2: [[256,20],[100,0]]} #{D3: [[256,20],[16,0],[16,0]]}
  dirs: [X]
noises:
  - Normal:
      name: xi
symbols:
  - Constant:
      name: D
      value: 1
  - PDEs:
      - dvar: u
        expr: ["D*(u[(x+1)%x_size+y*x_size]-2*u[x+y*x_size]+u[(x+x_size-1)%x_size+y*x_size])*ivdx*ivdx + sqrt(2*D*ivdx*ivdt)*(xi[(x+1)%x_size+y*x_size]-xi[x+y*x_size])*ivdx"]
integrator:
  Euler:
    dt: 0.001
